### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by SuperJMN** [hawkerm/monaco-editor-uwp#17]
I'm creating a little debugger for my own assembly language. I would like to highlight a given line in the editor (by id).

Is there any way to do it?
Thank you :)

**Comment by hawkerm** [comment]
Yup, the little test app shows that here: https://github.com/hawkerm/monaco-editor-uwp/blob/master/MonacoEditorTestApp/MainPage.xaml.cs#L164

```
     this.Editor.Decorations.Add(
                new IModelDeltaDecoration(new Range(4, 1, 4, 1), new IModelDecorationOptions() {
                    IsWholeLine = true,
                    ClassName = new CssLineStyle()
                    {
                        BackgroundColor = new SolidColorBrush(Colors.AliceBlue)
                    },
```

The `Range` object tells it which line to highlight, the 2nd and 4th column numbers will be ignored.

You can cache the CssLineStyle for efficiency too (otherwise it'll create a new style in the internal WebView each time you set a line).
