### ISSUE TITLE
Find code feature

### ISSUE THREAD

**Issue by DmitryBorodiy** [hawkerm/monaco-editor-uwp#71]
Hello!
I'm looking for an opportunity how can I implement the ability to search for text and code in the editor?

Thank you!

**Comment by hawkerm** [comment]
@DmitryBorodiy the Monaco editor already has the ability for the user to search using `Ctrl+F`.

Otherwise, if you're asking about how you can introspect what has been written in the editor, please look at the sample app and the code in this repo. It's the same API as Monaco itself which provides the `FindMatches` API off the model to look at text in the editor.

**Comment by DmitryBorodiy** [comment]
How I can use FindMatches method?

**Comment by DmitryBorodiy** [comment]
I cant find this method in Model...

**Comment by hawkerm** [comment]
@DmitryBorodiy there's an example in the demonstration app right here:

https://github.com/hawkerm/monaco-editor-uwp/blob/ba3c0de6ad95527b0cb6a9dac9c6c2098382dfc9/MonacoEditorTestApp/MainPage.xaml.cs#L535

**Comment by DmitryBorodiy** [comment]
> @DmitryBorodiy there's an example in the demonstration app right here:
> 
> https://github.com/hawkerm/monaco-editor-uwp/blob/ba3c0de6ad95527b0cb6a9dac9c6c2098382dfc9/MonacoEditorTestApp/MainPage.xaml.cs#L535

Thank you I try it!🙂
